[package]
name = "h3m"
version = "0.1.0"
authors = ["Andriy S. on cobalt <sima.rv@gmail.com>"]

[dependencies]
nom = "4.0.0-beta1"
flate2 = "*"
colored = "*"
clap = "*"

[features]
default = ["put"]
put = []
